name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write  # needed for GHCR push

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build uber JAR
        run: ./gradlew :app:uberJar --stacktrace

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-blockchain-jar
          path: app/build/libs/*-all.jar

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/libs/*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    needs: publish-jar
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jiany-s/java-blockchain:latest
            ghcr.io/jiany-s/java-blockchain:${{ github.ref_name }}
